### ISSUE TITLE
readme.md has broken link

### ISSUE THREAD

**Issue by borgified** [assimilation/assimilation-official#13]
broken
http://linux-ha.org/source-doc/assimilation/html/md__r_e_a_d_m_e.html

**Comment by Alan-R** [comment]
This sounds like a problem for @h4ck3rm1k3 to fix...

**Comment by h4ck3rm1k3** [comment]
sure thing

**Comment by h4ck3rm1k3** [comment]
when I run make doc 
it produces this file in doxygen md__r_e_a_d_m_e.html

I would suggest to just replace it with :
http://linux-ha.org/source-doc/assimilation/html/index.html

**Comment by Alan-R** [comment]
I can't seem to get Doxygen to format the markdown. I don't want to spend more time on it, so I just pointed it at the github README. Feel free to look into it some more. this fix is now in the github repository.

**Comment by h4ck3rm1k3** [comment]
see my patch, I think this pointer to the readme is not needed.

On Tue, Oct 6, 2015 at 7:05 AM, Alan Robertson <notifications@github.com>
wrote:

> I can't seem to get Doxygen to format the markdown. I don't want to spend
> more time on it, so I just pointed it at the github README. Feel free to
> look into it some more. this fix is now in the github repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/issues/13#issuecomment-145823436>
> .
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by Alan-R** [comment]
So I missed your pull request. Sorry!

I was there fixing something else much more visible than that - so I
made the change while I was there.

On 10/06/2015 05:24 AM, James Michael DuPont wrote:
> see my patch, I think this pointer to the readme is not needed.
>
> On Tue, Oct 6, 2015 at 7:05 AM, Alan Robertson <notifications@github.com>
> wrote:
>
> > I can't seem to get Doxygen to format the markdown. I don't want to
> spend
> > more time on it, so I just pointed it at the github README. Feel free to
> > look into it some more. this fix is now in the github repository.
> >
> > —
> > Reply to this email directly or view it on GitHub
> >
> <https://github.com/assimilation/assimilation-official/issues/13#issuecomment-145823436>
> > .
> >
>
>
>
> -- 
> James Michael DuPont
> Kansas Linux Fest http://kansaslinuxfest.us
> Free/Libre Open Source and Open Knowledge Association of Kansas
> http://openkansas.us
> Member of Free Libre Open Source Software Kosova http://www.flossk.org
> Saving Wikipedia(tm) articles from deletion
> http://SpeedyDeletion.wikia.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/issues/13#issuecomment-145826143>.
>


-- 

Alan Robertson / CTO
AlanR@AssimilationSystems.com <mailto:AlanR@AssimilationSystems.com>/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter <https://twitter.com/ossalanr> Linkedin
<https://www.linkedin.com/in/alanr> skype
<https://htmlsig.com/skype?username=alanr_unix.sh>
