### ISSUE TITLE
pinger is now included by testify tests - don't need to do it separately in Travis.ci build

### ISSUE THREAD

**Issue by Alan-R** [assimilation/assimilation-official#17]
So, you don't need to run it in a separate step.

I don't remember why you put the *netconfig* discovery in the stream. If you're going to run them, I'd discovery commands before the build step. That way if things mess up, we'll have that information available.

From my perspective, you might run the *os* discovery. It's probably more interesting to know if something goes wrong.

**Comment by borgified** [comment]
ah makes sense. yea been doing that forever just following the original design blindly :)
