### ISSUE TITLE
need to update buildtools/assimDnI

### ISSUE THREAD

**Issue by borgified** [assimilation/assimilation-official#26]
logic based on getting the tarball from mercurial
http://hg.linux-ha.org/|experimental/assimilation/archive

but i dont know what the github counterparts of experimental/assimilation/archive are

**Comment by Alan-R** [comment]
I'm not sure what the question is... Where is the text that gives the steps that you can't figure out.

Is the question "how to get a development tarball from Github?"

Then the answer to that is:
wget https://github.com/assimilation/assimilation-official/archive/master.tar.gz

Is the question, "How to get a release tarball from Github?"
Then the answer to that is:
wget https://github.com/assimilation/assimilation-official/archive/v1.1.2.tar.gz
or more generally

wget https://github.com/assimilation/assimilation-official/archive/<version-tag>.tar.gz
or wget https://github.com/assimilation/assimilation-official/archive/v<version-number>.tar.gz

Does that help?

**Comment by Alan-R** [comment]
Not quite sure what the question is here. I'm missing some context. Where does this occur?


For the latest version (HEAD/tip/frontier/master/whatever) of the tree, it looks like this:
`wget https://github.com/assimilation/assimilation-official/archive/master.tar.gz`

For a release, it looks like this:
`wget https://github.com/assimilation/assimilation-official/archive/v1.1.2.tar.gz`

Does this answer your question?

**Comment by borgified** [comment]
just a remider for myself for fix: https://github.com/assimilation/assimilation-official/blob/master/buildtools/assimDnI at some point because it's still referring to mercurial to fetch the tarball

**Comment by Alan-R** [comment]
This is obsolete. Everything has changed since then.
