### ISSUE TITLE
created travisci branch

### ISSUE THREAD

**Issue by borgified** [assimilation/assimilation-official#3]
d9b4504c2fee8f6a6f667cfb56a606f2b95d497a
i added the .travis.yml here and enabled travis to listen to pushes to the repo. once we iron out all the errors, i can merge this to master.

the builds can be seen here: https://travis-ci.org/assimilation/assimilation-official/

and this is the latest build log (with errors): https://travis-ci.org/assimilation/assimilation-official/builds/80584496

ignore the twitter message i sent @Alan-R , thats old now

**Comment by Alan-R** [comment]
Wow! I've never seen anything like that...


On 09/16/2015 01:37 AM, Fwiffo wrote:
>
> d9b4504
> <https://github.com/assimilation/assimilation-official/commit/d9b4504c2fee8f6a6f667cfb56a606f2b95d497a>
> i added the .travis.yml here and enabled travis to listen to pushes to
> the repo. once we ironed out all the errors, i can merge this to master.
>
> the builds can be seen here:
> https://travis-ci.org/assimilation/assimilation-official/
>
> and this is the latest build log (with errors):
> https://travis-ci.org/assimilation/assimilation-official/builds/80584496
>
> ignore the twitter message i sent you, thats old now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/issues/3>.
>


-- 

Alan Robertson / CTO
AlanR@AssimilationSystems.com <mailto:AlanR@AssimilationSystems.com>/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter <https://twitter.com/ossalanr> Linkedin
<https://www.linkedin.com/in/alanr> skype
<https://htmlsig.com/skype?username=alanr_unix.sh>

**Comment by Alan-R** [comment]
You're using a *really* old version of neo4j: USING NEO4J VERSION (1, 9,
4). I really need 2.0 or better, and don't currently know any reason to
use anything but the latest version.

Konsole output
Here's what I've been testing with:

Neo4j version 2.2.5 // py2neo version 2.0.7 // Python version 2.7.9 //
java version "1.7.0_79"




On 09/16/2015 01:37 AM, Fwiffo wrote:
>
> d9b4504
> <https://github.com/assimilation/assimilation-official/commit/d9b4504c2fee8f6a6f667cfb56a606f2b95d497a>
> i added the .travis.yml here and enabled travis to listen to pushes to
> the repo. once we ironed out all the errors, i can merge this to master.
>
> the builds can be seen here:
> https://travis-ci.org/assimilation/assimilation-official/
>
> and this is the latest build log (with errors):
> https://travis-ci.org/assimilation/assimilation-official/builds/80584496
>
> ignore the twitter message i sent you, thats old now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/issues/3>.
>


-- 

Alan Robertson / CTO
AlanR@AssimilationSystems.com <mailto:AlanR@AssimilationSystems.com>/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter <https://twitter.com/ossalanr> Linkedin
<https://www.linkedin.com/in/alanr> skype
<https://htmlsig.com/skype?username=alanr_unix.sh>

**Comment by borgified** [comment]
OK I'll try to see if there's some way to get a newer version of neo4j on there.

**Comment by borgified** [comment]
ok neo4j problem solved.. now theres 1 testify test failing.. let u hunt this one down
https://travis-ci.org/assimilation/assimilation-official/builds/80973138

**Comment by Alan-R** [comment]
That should be fixed now.

Thanks JC!

**Comment by Alan-R** [comment]
../../discovery_agents/sudoers: 383: ../../discovery_agents/sudoers: 
_*line: not found*_

/tmp/18521.testout 
/home/travis/build/assimilation/assimilation-official/cma/../testcode/discovery_output/sudoers 
differ: byte 1930, line 45

ERROR: Discovery output sudoers was incorrect (has changed).

Diff -u follows

What platform is this? I can rewrite it without the "line" command... 
*head -n 1* would work.

**Comment by borgified** [comment]
i created a new directory called ../ci where i store some extra stuff i couldnt put into .travis.yml hope that is ok

**Comment by Alan-R** [comment]
Do you want to put that under the build tools directory? 

On September 18, 2015 11:27:41 AM MDT, Fwiffo <notifications@github.com> wrote:
>i created a new directory called ../ci where i store some extra stuff i
>couldnt put into .travis.yml hope that is ok
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/assimilation/assimilation-official/issues/3#issuecomment-141513799

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Alan-R** [comment]
I think that would be awesome. Make the ci directory under it?

On September 18, 2015 1:02:17 PM MDT, Alan Robertson <alanr@assimilationsystems.com> wrote:
>Do you want to put that under the build tools directory? 
>
>On September 18, 2015 11:27:41 AM MDT, Fwiffo
><notifications@github.com> wrote:
>>i created a new directory called ../ci where i store some extra stuff
>i
>>couldnt put into .travis.yml hope that is ok
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/assimilation/assimilation-official/issues/3#issuecomment-141513799
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
