### ISSUE TITLE
Create nanoprobe packages with FPM

### ISSUE THREAD

**Issue by Alan-R** [assimilation/assimilation-official#71]
For a variety of platforms - specifically CentOS, Ubuntu/Debian, SUSE, others as needed...

But start with CentOS and Ubuntu (or Debian)

For more info about FPM:
- https://github.com/jordansissel/fpm
- https://fpm.readthedocs.io/en/latest/

**Comment by borgified** [comment]
deb: https://github.com/assimilation/assimilation-official/pull/73

**Comment by borgified** [comment]
rpm: #74
