### ISSUE TITLE
travis-ci builds fail due to sudoers command

### ISSUE THREAD

**Issue by Alan-R** [assimilation/assimilation-official#9]
The symptoms point to sort giving different results on different platforms - without any errors being indicated.  https://travis-ci.org/assimilation/assimilation-official/builds/81379935

The only thing I know of that could possibly cause that is the locale. Sort command man page suggests setting LC_ALL=C. So I'm trying that.

**Comment by borgified** [comment]
what's the expected discovery output of sudoers vs what is actually being output? i cant see it from the build log

**Comment by Alan-R** [comment]
Here's the chunk of build output. You can find it pretty quickly by searching for "sudoers"

     "Defaults": {
-          "ANY": {"syslog": "auth"},
-          "command:PAGERS": {"noexec": true},
           "user:FULLTIMERS": {"lecture": false},
           "user:millert": {"authenticate": false},
+          "command:PAGERS": {"noexec": true},
           "runas:root": {"set_logname": false},
-          "system:SERVERS": {"log_year": true, "logfile": "/var/log/sudo.log"}
+          "system:SERVERS": {"log_year": true, "logfile": "/var/log/sudo.log"},
+          "ANY": {"syslog": "auth"}
     },

I just pushed a change that sets LC_ALL='C' - which should make sort always behave the same way...

**Comment by Alan-R** [comment]
That appears to have fixed it.

**Comment by borgified** [comment]
awesome. green is my favorite color too!
